runner: "research.muP_MoE.train.train"

# time: "05:00:00"
time: "00:20:00"

n_gpus: 1
cpus_per_gpu: 16

interactive_debug: false

params:
  name: "muP_MoE_10_step"
  # tags: ["muP_MoE", "muTransfer", "norm_plot_3"]
  tags: ["muP_MoE", "muTransfer", "10_step", "kc_version_2", "like_blog", "many_heads"]

  mup_params:
    ^alpha_in: [20.0]
    ^alpha_out: [0.05]
    # alpha_in: 5.0
    # alpha_out: 0.2
    base_dmodel: 128

  # training
  n_steps: 10
  lr_warmup_steps: 0
  batch_size: 64
  cutoff: 128

  # model
  model_type: gpt
  # dmodel: 32
  ^dmodel: [128, 256, 512, 1024, 2048]
  dff_ratio: 4
  n_blocks: 2
  n_att_heads: 16
  attention_mode: 'vanilla'
  attention_normalization: 'dhead'
  ff_mode: vanilla
  use_torch_bmm: true

  # learning
  scheduler: constant
  learning_rate: 1e-2
  final_lr_fraction: 0.1
  grad_clip: 0.5
  weight_decay: 0.01
  init_scale: 0.2
  init_type: truncated_normal
  capacity_factor: 1.0

  # aux losses
  load_balancing_loss_weight: 0.01
  # zloss_weight: 0.001

  # FSDP
  # fsdp_enabled: true
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # fsdp_selective_precision_modules: "AttentionMechanism,RoPE"

  # other
  dataset_type: c4
  mixed_precision: true
  flash_attention: true
  mixed_precision_dtype: bfloat16
  ^data_seed: [101, 102, 103, 104, 105]

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1
  # logging_interval_light: 50
  # logging_interval_loss: 20
  # save_weights_interval: null

  # debug
  # logger_types: "stdout"
  # n_steps: 100
  # batch_size: 8
  # cutoff: 16
  # use_dummy_dataset: true
  # n_blocks: 2
  # dmodel: 16
  # n_att_heads: 2
