parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
n_gpus: 2
time: "0-00:20:00"
skip_copy_code: true
params:
    batch_size_rampup_transition_points: [0.0000655, 0.0002455]
    batch_size_rampup_sizes: [128, 256]
    batch_size: 512
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
    gradient_accumulation_steps: 8
    ff_mode: vanilla
    dataset_type: c4
    n_steps: 7500
    learning_rate: 5e-4
    name: bs_rampup
    tags: [bs_rampup_test]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
