parent: configs/baselines/gpt/dense/mini.yaml
md5_parent_hash: f181bf20ef729beb781a926a284a7e4f
n_gpus: 8
n_nodes: 2
time: "0-00:45:00"
params:
    num_workers: 4
    data_seed: -1
    n_tokens: null
    n_steps: 1000    
    ^batch_size: [512]
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
    gradient_accumulation_steps: 4
    ff_mode: vanilla
    dataset_type: c4
    learning_rate: 5e-4
    lr_warmup_steps: 100
    final_lr_step: 1000
    final_lr_fraction: 0.1
    name: multi_node_example
    tags: [final_multinode]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
