parent: configs/baselines/gpt/dense/6b.yaml
md5_parent_hash: cdcde52ce07503e2da38c1bf718a9f96
n_gpus: 32
n_nodes: 8
time: "0-00:30:00"
params:
    num_workers: 4
    data_seed: -1
    n_tokens: null
    n_steps: 100    
    ^batch_size: [512]
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    # activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
    gradient_accumulation_steps: 1
    ff_mode: vanilla
    dataset_type: c4
    learning_rate: 5e-4
    name: multi_node_example
    tags: [multinode_4_workers]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
