parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
n_gpus: 8
n_nodes: 2
time: "0-01:00:00"
params:
    num_workers: 4
    data_seed: -1
    n_tokens: null
    n_steps: 100    
    batch_size: 512
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
    gradient_accumulation_steps: 1
    ff_mode: vanilla
    dataset_type: c4
    learning_rate: 5e-4
    name: multi_node_example
    tags: [multinode_4_workers]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
