all_config_paths: /home/szymonantoniak/PycharmProjects/llm-random/research/conditional/tests/../train/configs/test/test_baseline.yaml
batch_size: 4
cpus_per_gpu: 8
cuda_visible: ''
cutoff: 16
dataset_type: wikibook
dff: 256
dmodel: 64
ff_mode: vanilla
grad_clip: 0.5
gres: gpu:1
hf_datasets_cache: /home/szymonantoniak/.cache/huggingface/datasets
learning_rate: 0.0001
logging_interval_heavy: 2
logging_interval_loss: 1
lr_decay: 0.8
lr_decay_interval: 10000
lr_warmup_steps: 0
mixed_precision: true
model_type: bert
n_att_heads: 4
n_blocks: 2
n_gpus: 0
n_steps: 3
name: baseline_test
nodelist: null
path_to_entry_config: /home/szymonantoniak/PycharmProjects/llm-random/research/conditional/tests/../train/configs/test/test_baseline.yaml
project_name: pmtest/llm-random-tests
runner: research.conditional.train.cc_train
runs_multiplier: 1
singularity_image: /home/szymonantoniak/images/sparsity_2023.08.29_09.26.31.sif
tags:
- test
- model_type=bert
- ff_mode=vanilla
time: 5-05:00:00
use_neptune: true
