time: 0-40:00:00
interactive_debug_session: false
runner: research.conditional.train.cc_train

n_gpus: 1

params:
  name: "kan_init_tune"
  save_weights_interval: -1
  tags: [kan, kan_grid, init_grid]

  logger_types: "neptune"
  project_name: pmtest/llm-random

  fsdp_enabled: false
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE,ExpertGatingOld,TokenChoiceRouterOld"
  batch_size: 128 # 128
  cutoff: 128
  final_lr_fraction: 0.1
  scheduler: cosine
  final_lr_step: 20000
  n_steps: 20200
  lr_warmup_steps: 200
  grad_clip: 1.0
  weight_decay: 0.01  # mby 0?
  ^learning_rate: [5e-3]
  # learning_rate: 5e-4
  logging_interval_heavy: 200
  logging_interval_loss: 50
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  torch_compile: false
  loss_checkpoint_chungs: 8

  dataset_type: c4

  # MODEL
  model_type: gpt
  activation_type: relu
  dmodel: 768
  n_att_heads: 12
  n_blocks: 12

  # medium size
  dmodel: 512
  dff: 2048
  n_blocks: 8
  n_att_heads: 8

  # # mini size
  dmodel: 256
  dff: 1024
  n_blocks: 4
  n_att_heads: 4

  final_lr_step: 10000
  n_steps: 10100
  lr_warmup_steps: 100
  logging_interval_heavy: 200
  logging_interval_loss: 50

  ^ff_mode: [mlp_kan]
  use_torch_bmm: true
  softmax_over: experts

  # init
  # ^kan_latent_factor: [1.0, 1.1, 1.2, 1.3, 1.5]
  kan_parameter_matched: 'true'
  init_scale: 0.1
  init_type: truncated_normal
  init_scale_base: 0.1
  init_scale_spline: 0.1
  ^init_scale_noise: [0.005, 0.01, 0.02, 0.05]

  # debug
  # logger_types: "stdout"
  # use_dummy_dataset: true
  # n_blocks: 1
  # n_att_heads: 1
  # zloss_weight: 0

  # dmodel: 16
  # n_blocks: 1
  # n_att_heads: 2