
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: ea24ed4a5d6558970d3230b69a0c88fa
time: 1-00:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm2048", "doner"]

  ^learning_rate: [0.0000625, 0.000125, 0.00025]
  
  dmodel: 2048
  dff: 2048
  n_steps: 124_261
  learning_rate: 0.0005

  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/