
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3d46d5a14eb873ef5bcd6a6438fc8304
time: 4-00:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "large", "doner"]
  
  dmodel: 2048
  dff: 2048
  n_steps: 108_800
  learning_rate: 0.0005

  dont_save_final_model: False
  save_weights_path: /local_storage_1/ms_tmp/models/