
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm512", "inverted_test"]

  dmodel: 512
  dff: 512
  projected_dmodel: 512
  projected_dff: 512
  # n_steps: 19_545 # same as dmodel
  n_steps: 1000 # same as dmodel
  learning_rate: 0.0005 # same as dmodel
  # ^learning_rate: [0.00025, 0.0005, 0.001]

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  

  projection_init_type: inverted_test
  # ^projection_init_type: [half, orthogonal]
  no_projected_head: False
  # ^no_projected_head: [True, False]

  projected_distillation: True
  projected_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-24_18-16-36/None/1171839/19545.pt
  

  # fsdp_use_orig_params: True
  # fsdp_enabled: True
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"





