
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 426d38a67881ad9b9276b25286a1ce31
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "small", "all_distillation"]

  dmodel: 256
  dff: 256
  projected_dmodel: 512
  projected_dff: 512
  n_steps: 1600
  learning_rate: 0.0005

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias

  # ^residual_mode: [pre_norm_no_bias, pre_norm]
  
  projection_init_type: null
  # projection_init_type: random
  # projection_init_type: sum1d
  # projection_init_type: half
  # projection_init_type: orthagonal
  # projection_init_type: col1
  # projection_init_type: asd
  # ^projection_init_type: [orthagonal, col1]
  # ^projection_init_type: [null, random, sum1d, half, orthagonal, col1]

  projected_distillation: True
  projected_weights_path: /local_storage_1/ms_tmp/models/41986/12800.pt # no_bias_layer_norm and no_ff_bias
  
  # save_weights_path: /local_storage_1/ms_tmp/models/
  save_weights_path: null







