arent: research/conditional/train/configs/baselines/expert_choice/common.yaml
md5_parent_hash: cbdf4e5992f41713488c25c819086e51
name: "expert_choice_medium"

params:
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
