parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 7d5daa403319ec12a78266a728814fc0
name: "expert_choice_small"

params:
  dmodel: 512
  n_blocks: 4
  n_att_heads: 8
