parent: configs/baselines/gpt/expert_choice/granularity/4/mini.yaml
md5_parent_hash: 8c55b8c4ca676c8235c39a0555debad3
time: 0-05:00:00
interactive_debug_session: false

params:
  name: "laptop_check"
  ff_mode: expert_choice
  torch_compile: false
  mixed_precision_dtype: "float16"
  moe_inner_expert: ff
  activation_type: relu
  granularity: 1

  save_weights_interval: -1
  # ^use_principled_moe: [true, false]
  ^use_principled_moe: [false]
  use_dummy_dataset: true
