parent: research/conditional/train/configs/baselines/gpt/dense/large.yaml
md5_parent_hash: 31bfb1fc00a01fe9b430cb1223ed9af4
time: 7-00:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1
