
parent: configs/projected_dis/common.yaml
md5_parent_hash: 49ce21414901578ae2d5e0bbbe097c10
time: 0-02:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "medium"]

  # ^dmodel: [512, 512]
  dmodel: 512
  dff: 2048
  n_steps: 12_800

  # save_weights_path: /local_storage_1/ms_tmp/models/

  # fsdp_enabled: false

  # fsdp_enabled: true
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
