runner: "research.tokenizex.train.train"
n_gpus: 1
cpus_per_gpu: 10
interactive_debug: false
time: "0-02:00:00"
cuda_visible: "7"
argparse: "research.tokenizex.utils.argparse"

params:
  name: tokenizex_large
  tags: ["ms", "tokenizex", "large"]

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_path: "tokenizex_model_ckpt"
  save_weights_interval: 25_000
  decoding_interval: 25000
  eval_interval: 200

  # model
  dmodel: 1024
  dff: 2048
  n_blocks: 24
  n_att_heads: 16
  cutoff: 256

  # training
  n_steps: 100_000
  init_type: kaiming_uniform
  init_scale: 1.0

  learning_rate: 1e-4
  final_lr_step: 100_000
  lr_warmup_steps: 2500
  scheduler: cosine
  final_lr_fraction: 0.1
  grad_clip: 0.5
  dataset_type: wikibook
  batch_size: 64



  # tokenizex
  input_wise_positional_embedding: True  
