parent: configs/mole/common.yaml
md5_parent_hash: c7e284c7ce24a161e67f2011d5b49190
time: 0-17:50:00
# n_gpus: 2
n_gpus: 4 # athena

# cpus_per_gpu: 20 # writer
# cpus_per_gpu: 25 # entropy
cpus_per_gpu: 16 # athena

params:
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  n_steps: 43_200

  name: "MoLE"
  tags: ["mole", "base", "G3"]

  ^biased_balancing_loss_weight: [0]
  ^load_balancing_loss_weight: [0.0625]
  learning_rate: 0.00025

  # num_workers: 14 # entropy
  num_workers: 16 # athena, writer