parent: configs/mole/common.yaml
time: 0-20:50:00
n_gpus: 1
# n_gpus: 2 # athena
cpus_per_gpu: 26 # writer
# cpus_per_gpu: 32 # entropy
# cpus_per_gpu: 16 # athena
md5_parent_hash: 5060b43ec5784557e7867ff9b5ad3ac3

params:
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  n_steps: 43_200
  final_lr_step: 43_200

  name: "MoLE"
  tags: ["mole", "base", "first_run"]

  ^biased_balancing_loss_weight: [0, 0.015625]
  ^load_balancing_loss_weight: [0.015625]
  pos_grouped: "{'NOUN':[0,9],'PUNCT':[9,14],'VERB':[14,19],'ADP':[19,24],'PROPN':[24,28],'DET':[28,32],'ADJ':[32,35],'PRON':[35,38],'AUX':[38,40],'ADV':[40,42],'CCONJ':[42,44],'PART':[44,45],'NUM':[45,46],'EOT':[46,47],'SPACE':[46,47],'SYM':[46,47],'X':[46,47],'INTJ':[46,47],'SCONJ':[47,48],}"
  expansion_rate: 48
  learning_rate: 0.0005
  # ^learning_rate: [0.00025, 0.0005, 0.001]

  num_workers: 24 # writer
  # num_workers: 15 # entropy
  # num_workers: 16 # athena