parent: configs/mole/common.yaml
time: 0-20:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: f46521584cb698bb67ed75c907d2eb38

params:
  name: "MoLE"
  tags: ["mole", "ms", "grid_1"]
  ^biased_balancing_loss_weight: [0, 0.0001, 0.0002, 0.0005, 0.001, 0.002, 0.0039, 0.0078, 0.0156, 0.0312, 0.0625, 0.125, 0.25, 0.5, 1.0]
  ^load_balancing_loss_weight: [0, 0.0001, 0.0002, 0.0005, 0.001, 0.002, 0.0039, 0.0078, 0.0156, 0.0312, 0.0625, 0.125]
  