parent: configs/mole/common.yaml
time: 0-05:00:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 5060b43ec5784557e7867ff9b5ad3ac3

params:
  name: "MoLE_grid_nl"
  tags: ["mole", "hash", "new_loss_1", "sparse_grid", "softmax"]
  ^biased_balancing_loss_weight: [1.0, 0.5, 0.25, 0.125, 0.0625, 0.03125, 0.015625, 0.0078125, 0.00390625, 0.001953125, 0.0009765625, 0.00048828125, 0.000244140625]
  ^load_balancing_loss_weight: [0.015625]
  biased: hash_token
  pos_grouped: "{'A':[0,1],'A':[1,2],'A':[1,2],'A':[1,2],'A':[1,2],'A':[1,2],'A':[1,2],'A':[1,2]}"
  expansion_rate: 48
  
  num_workers: 16