parent: configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 27e0212d49a74700ba49088f6410580d
time: 1-00:00:00

params:
  name: "expert_choice_medium"
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
