parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
time: "2-00:00:00"
runner: "research.token_reduction.runner"
n_gpus: 1

params:
  name: "base_merging_scheduled_reduced_1232_to_1024"
  tags: ["base", "merging", "scheduled","80c_10l_10n"]
  wandb_project: "token_reduction"

  ^reduction_layer_type: ["merging"]
  ^reduced_number_of_tokens: [1024]
  ^cutoff: [1232]
  ^batch_size: [256]
  ^learning_rate: [1e-3]
  gradient_accumulation_steps: 4
  reduction_layer_scheduler_params: "[[0,25600,208],[25601,28800,208,0],[28801,32000,0]]"


  n_steps: 32_000 #TODO replace with correct number of steps
  final_lr_step: 32_000
  lr_warmup_steps: 320
  final_lr_fraction: 0.1


  # precision / distributed
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true

  # common
  scheduler: cosine
  init_type: truncated_normal
  init_scale: 0.1
  dataset_type: c4
  weight_decay: 0.1
  grad_clip: 1.0
  logger_types: "neptune,wandb"

  # intervals
  decoding_interval: 0
  logging_interval_heavy: 1000
  logging_interval_light: 100
  save_weights_interval: 0
  eval_interval: 100  