runner: "research.tokenizex_comp.train.train"
n_gpus: 1
cpus_per_gpu: 16
interactive_debug: false
time: "0-08:00:00"
cuda_visible: "7"


params:
  name: "tokenizex_baseline_medium"
  tags: ["ms", "tokenizex", "baseline", "medium"]

  model_type: gpt
  
  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_path: "default_model_ckpt"
  save_weights_interval: 25_000
  decoding_interval: 25000
  
  # model
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12 
  cutoff: 256

  # training
  n_steps: 50_005
  init_type: kaiming_uniform
  init_scale: 1.0

  learning_rate: 1e-4
  final_lr_step: 50_005
  lr_warmup_steps: 2500
  scheduler: cosine
  final_lr_fraction: 0.1
  grad_clip: 1.0
  dataset_type: wikibook
  batch_size: 512
  gradient_accumulation_steps: 4
  