parent: configs/experiments/constrained_scaling_laws/190M/model.yaml
md5_parent_hash: 2d869341e25fbb090df80b68a7091fbf
time: "48:00:00"
n_gpus: 1
params:
  name: scheduler_trapezoidal
  tags: ["mstest", "190M", "trapezoidal_scheduler", "grid"]
  expansion_rate: 8
  ^learning_rate: [0.0005, 0.001, 0.002, 0.004, 0.008]
  ^n_steps: [8700, 17400, 43500]
  ^scheduler: [trapezoidal, cosine]
  lr_warmup_fraction: 0.01
  lr_trapezoidal_decay_fraction: 0.2
  data_seed: 44


