parent: configs/experiments/constrained_scaling_laws/85M/model.yaml
md5_parent_hash: 901c724a94130d2f6e4a84252b67ee78
time: "48:00:00"
n_gpus: 1
params:
  name: scheduler_trapezoidal
  tags: ["mstest", "85M", "trapezoidal_scheduler", "grid"]
  expansion_rate: 8
  ^learning_rate: [0.0005, 0.001, 0.002, 0.004, 0.008]
  ^n_steps: [2600, 5200, 13000]
  ^scheduler: [trapezoidal, cosine]
  lr_warmup_percent: 0.01
  lr_trapezoidal_decay_fraction: 0.2
  data_seed: 44
  fsdp_enabled: false

  # name: scheduler_trapezoidal
  # tags: ["mstest", "85M", "trapezoidal_scheduler", "test"]
  # expansion_rate: 8
  # n_steps: 10
  # lr_warmup_percent: 0.1
  # ^lr_trapezoidal_decay_fraction: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  # # lr_trapezoidal_decay_fraction: 0.1
  # scheduler: trapezoidal
  # fsdp_enabled: false


