parent: configs/experiments/constrained_scaling_laws/25M/model.yaml
md5_parent_hash: 3067b2550c57a4b87c0c6a1287e6d902
time: "00:05:00"
n_gpus: 1
# n_gpus: 4
cpus_per_gpu: 8
# here configure GPUs & time for a given cluster for it to fit
params:
  name: "ms_repeater"
  tags: ["ms", "repeater", "test"]
  expansion_rate: 8
  n_steps: 2000
  batch_size: 100
  cutoff: 256
  # ^loss_checkpoint_chungs: [0, 0, 0]
  loss_checkpoint_chungs: 0
  save_weights_path: "./test_saving"
  save_weights_interval: 100
  # load_weights_path: "/home/ubuntu/llm-random-group/llm-random-cemetery/test_checkpoint_saving_4gpu_bs1024_2024-09-07_00-03-12/test_saving/rzckmcczmb/200.pt"
  # load_weights_path: "/home/ubuntu/llm-random-group/llm-random-cemetery/test_checkpoint_saving_4gpu_bs1024_2024-09-07_00-03-12/test_saving/rzckmcczmb/200.pt"
