parent: configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 1706dd43c527be74a6282b0319e9c31e
time: "2-00:00:00"
runner: "research.token_reduction.runner"
n_gpus: 1

params:
  name: "medium_dropping_1024_v2"
  logger_types: "neptune,wandb"
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true
  grad_clip: 1.0
  tags: ["medium", "token_reduction", "merging"]

  wandb_project: "token_reduction"
  final_lr_step: 75_000
  scheduler: cosine
  lr_warmup_steps: 750
  final_lr_fraction: 0.1
  n_steps: 75_000
  decoding_interval: 0
  logging_interval_heavy: 1000
  init_type: truncated_normal
  init_scale: 0.1
  save_weights_interval: 0
  dataset_type: c4
  weight_decay: 0.1
  eval_interval: 100  

  ##### Mode change ##########
  reduction_layer_type: "dropping"

  # reduction_layer_type: "merging"
  # gradient_accumulation_steps: 2

  #### Baseline params #####
  # cutoff: 2048
  # batch_size: 32
  # learning_rate: 5e-5

  # # cutoff: 1024
  # batch_size: 64
  # learning_rate: 1e-4

  ##### Token reduction params #####
  ^cutoff: [1126, 1232, 1536, 2048]
  reduced_number_of_tokens: 1024
  batch_size: 64
  learning_rate: 1e-4

  # gradient_accumulation_steps: 2

  # ^cutoff: [2252, 2464, 3072, 4096]
  # reduced_number_of_tokens: 2048
  # batch_size: 32
  # learning_rate: 5e-5


  #### DEBUG ####
  # learning_rate: 5e-5
  # cutoff: 32
  # reduced_number_of_tokens: 24
  # batch_size: 8
  # dmodel: 32
  # dff: 128
  # n_blocks: 2
  # n_att_heads: 2
  # use_dummy_dataset: true
  # num_workers: 0
  # logger_types: "stdout"

