parent: configs/baselines/gpt/dense/large.yaml
md5_parent_hash: 66aa609ebcff1d88f0bb900b0a0966fb
time: "2-00:00:00"
runner: "research.token_reduction.utils.runner"
n_gpus: 2

params:
  name: "large_vanilla"
  tags: ["large", "vanilla", "token_reduction"]
  wandb_project: "token_reduction"


  ^cutoff: [1024] 
  batch_size: 256
  ^learning_rate: [5e-4]
  gradient_accumulation_steps: 2

  n_steps: 26400
  final_lr_step: 26400
  lr_warmup_steps: 264
  final_lr_fraction: 0.1


  # precision / distributed
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true

  # common
  scheduler: cosine
  init_type: truncated_normal
  init_scale: 0.1
  dataset_type: c4
  weight_decay: 0.1
  grad_clip: 0.1
  logger_types: "neptune"

  # intervals
  decoding_interval: 0
  logging_interval_heavy: 1000
  logging_interval_light: 100
  save_weights_interval: 0
  eval_interval: 100

  #fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism"

  log_update_norm_interval: 10